#!/bin/bash
# ============================================================
#  Ultron Installer
#  Installs the `ultron` command to ~/bin so you can call it
#  from anywhere like:  ultron "run ACT training for 3 hours"
# ============================================================

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo ""
echo "  Installing Ultron CLI..."
echo ""

# Create ~/bin if it doesn't exist
mkdir -p "$HOME/bin"

# Create the launcher wrapper (ultron.py loads .env itself)
LAUNCHER="$HOME/bin/ultron"
cat > "$LAUNCHER" << LAUNCHER_EOF
#!/bin/bash
# Ultron launcher — auto-generated by install.sh
exec python3 "$SCRIPT_DIR/ultron.py" "\$@"
LAUNCHER_EOF

chmod +x "$LAUNCHER"
echo "  ✓ Launcher installed at: $LAUNCHER"

# Create .env from the template on first install
if [ ! -f "$SCRIPT_DIR/.env" ]; then
    cp "$SCRIPT_DIR/.env.template" "$SCRIPT_DIR/.env"
    chmod 600 "$SCRIPT_DIR/.env"
    echo "  ✓ Created $SCRIPT_DIR/.env from the template"
fi

# Check ~/bin is in PATH
if [[ ":$PATH:" != *":$HOME/bin:"* ]]; then
    echo ""
    echo "  ⚠  ~/bin is not in your PATH."
    echo "  Add this to your ~/.bashrc or ~/.zshrc:"
    echo ""
    echo '      export PATH="$HOME/bin:$PATH"'
    echo ""
    echo "  Then run:  source ~/.bashrc"
fi

# Check dependencies
echo ""
echo "  Checking dependencies..."
python3 -c "import requests" 2>/dev/null && echo "  ✓ requests" || echo "  ✗ requests (run: pip install requests)"
python3 -c "import rich"     2>/dev/null && echo "  ✓ rich"     || echo "  ✗ rich     (run: pip install rich)"
CLAUDE_BIN="$(command -v claude || echo "$HOME/.local/bin/claude")"
[ -x "$CLAUDE_BIN" ]        && echo "  ✓ claude found ($CLAUDE_BIN) — log in once with: claude, then /login" || echo "  ✗ claude not found — install Claude Code, it is Ultron's main brain"
which sbatch &>/dev/null    && echo "  ✓ sbatch found"  || echo "  ✗ sbatch not found — are you on a SLURM node?"
which ollama &>/dev/null    && echo "  ✓ ollama found (local backup)"  || echo "  - ollama not in PATH (local backup model unavailable here)"

echo ""
echo "  ✓ Installation complete!"
echo ""
echo "  Next steps:"
echo "  1. Edit ultron/.env (Discord webhook, HF token) — see ultron/.env.template"
echo "  2. Edit ultron/config.py to set your SLURM partition & models"
echo "  3. Run:  ultron --dry-run \"run ACT training for 3 hours\""
echo "  4. Run:  ultron \"run ACT training for 3 hours\""
echo ""
