; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nucleo_g474re]
platform = ststm32
board = nucleo_g474re
framework = stm32cube
extra_scripts =
    linker_flags.py
    pre:freertos_build.py
; Build this submodule explicitly to exclude ports for other architectures.
lib_ignore = FreeRTOS-Kernel
build_flags = 
    -I include
	-Ilib/FreeRTOS-Kernel/include
	-Ilib/FreeRTOS-Kernel/portable/GCC/ARM_CM4F
    -Ilib/sh2
    -mfpu=fpv4-sp-d16
    -mfloat-abi=hard    